name: Compare
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    
jobs:
  compare-time-development:
    runs-on: ubuntu-latest
    steps:
      - name: Compare Development Time
        id: compare
        uses: padupe/action-content-change-validation@master
        with:
          authType: pat
          directoryOrFile: test
          githubToken: ${{ secrets.PAT_TOKEN }}
