name: Content Change Validation
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  content-change-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Content Change Validation
        uses: padupe/action-content-change-validation@1.1.2
        with:
          directoryOrFile: .github/workflows
          gitHubToken: ${{ secrets.PAT_TOKEN }}
