name: Content Change Validation
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  content-change-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Content Change Validation
        uses: padupe/action-content-change-validation@master
        with:
          authType: pat
          directoryOrFile: test
          gitHubPersonalAccessToken: ${{ secrets.PAT_TOKEN }}
